[[pages]]
path = "main.py"
name = "Agenda"
icon = "🏠"


[[pages]]
path = "pages/0_page_1.py"
name = "Importance of credit risk modeling"
icon = ":female-technologist:"

[[pages]]
name = "Role of ML in risk modeling"
icon = ":female-technologist:"
is_section = true

[[pages]]
path = "pages/1_Role_of_ML.py"
name = "Relevant factors/features"
icon = ""

[[pages]]
path = "pages/2_Metric.py"
name = "Metrics"
icon = ""

[[pages]]
path = "pages/3_Dataset.py"
name = "Dataset Exploration"
icon = ""

[[pages]]
path = "pages/4_Analysis.py"
name = "Analysing dataset"
icon = ""

[[pages]]
path = "pages/5_Missing_values.py"
name = "Handling missing values"
icon = ""

[[pages]]
path = "pages/6_Correlation.py"
name = "Identifying correlation"
icon = ""

[[pages]]
path = "pages/7_Encoding.py"
name = "Encoding"
icon = ""

[[pages]]
path = "pages/8_Modeling.py"
name = "Modeling Approaches"
icon = ""

[[pages]]
name = "Boosting"
icon = ":female-technologist:"
is_section = true

[[pages]]
path = "pages/9_Boosting_intro.py"
name = "Exercise-1: Run Decision Tree"
icon = ""

[[pages]]
path = "pages/10_Boosting_Intuition.py"
name = "Boosting Fundamentals"
icon = ""

[[pages]]
path = "pages/11_Why_Boosting.py"
name = "Gradient Boosting"
icon = ""

[[pages]]
path = "pages/12_Training_GBDT.py"
name = "Excercise-2 : Run Gradient Boosting Model"
icon = ""

[[pages]]
name = "Automated Hyperparameter tuning"
icon = ":male-technologist:"
is_section = true


[[pages]]
path = "pages/13_Optuna.py"
name = "Optuna"
icon = ""

[[pages]]
name = "Model Interpretation"
icon = ":male-technologist:"
is_section = true

[[pages]]
path = "pages/14_Model_Interpretation.py"
name = "Feature Importance using sklearn"
icon = ""

[[pages]]
path = "pages/15_Issues.py"
name = "Issues with sklearn interpretation"
icon = ""

[[pages]]
path = "pages/16_Issues_approach.py"
name = "Issues with approach"
icon = ""

[[pages]]
path = "pages/17_Challenges.py"
name = "Challenges"
icon = ":question:"
in_section = false
